import os
from google.cloud import bigquery
from typing import List, Dict, Optional, Any

# ==========================================
# 1. BigQuery Client Initialization
# ==========================================
# The client automatically detects credentials from the GOOGLE_APPLICATION_CREDENTIALS
# environment variable or your local gcloud authentication.
PROJECT_ID = "gradhack26jnb-408"
DATASET_ID = "HealthyFood"

client = bigquery.Client(project=PROJECT_ID)

def _get_table_ref(table_name: str) -> str:
    """Helper function to format the full BigQuery table/view reference."""
    return f"{PROJECT_ID}.{DATASET_ID}.{table_name}"

# ==========================================
# 2. User Profiles 
# ==========================================
def get_user_profile(user_id: str) -> Optional[Dict[str, Any]]:
    """Fetch user profile details from the user_profiles view."""
    table_ref = _get_table_ref("user_profiles")
    
    query = f"""
        SELECT *
        FROM `{table_ref}`
        WHERE user_id = @user_id
    """
    job_config = bigquery.QueryJobConfig(
        query_parameters=[
            bigquery.ScalarQueryParameter("user_id", "STRING", user_id)
        ]
    )
    
    results = client.query(query, job_config=job_config).result()
    
    # Return the first matching row as a dictionary
    for row in results:
        return dict(row)
    return None

# ==========================================
# 3. User Pantry Management
# ==========================================
def add_pantry_items(user_id: str, items: List[str]) -> bool:
    """Insert a list of ingredient names into a user's pantry."""
    table_ref = _get_table_ref("user_pantry")
    
    # Prepare data for insertion (Streaming Insert)
    rows_to_insert = [
        {"user_id": user_id, "ingredient_name": item} 
        for item in items
    ]
    
    # insert_rows_json is the standard method for streaming data into BigQuery
    errors = client.insert_rows_json(table_ref, rows_to_insert)
    
    if errors:
        print(f"Errors inserting into user_pantry: {errors}")
        return False
    return True

def get_user_pantry(user_id: str) -> List[str]:
    """Retrieve all pantry items for a specific user."""
    table_ref = _get_table_ref("user_pantry")
    
    query = f"""
        SELECT ingredient_name
        FROM `{table_ref}`
        WHERE user_id = @user_id
    """
    job_config = bigquery.QueryJobConfig(
        query_parameters=[
            bigquery.ScalarQueryParameter("user_id", "STRING", user_id)
        ]
    )
    
    results = client.query(query, job_config=job_config).result()
    
    # Extract just the ingredient names into a list
    return [row.ingredient_name for row in results]

# ==========================================
# 4. Recipe Management
# ==========================================
def save_recipe(user_id: str, recipe_name: str, recipe_text: str, missing_ingredients: str = "") -> bool:
    """Save a recipe generated by Gemini into the database."""
    table_ref = _get_table_ref("saved_recipes")
    
    rows_to_insert = [{
        "user_id": user_id,
        "recipe_name": recipe_name,
        "recipe_text": recipe_text,
        "missing_ingredients": missing_ingredients
    }]
    
    errors = client.insert_rows_json(table_ref, rows_to_insert)
    
    if errors:
        print(f"Errors inserting into saved_recipes: {errors}")
        return False
    return True

# ==========================================
# 5. Gamification / Rewards
# ==========================================
def get_rewards_catalog() -> List[Dict[str, Any]]:
    """Fetch all available rewards from the catalog."""
    table_ref = _get_table_ref("rewards_catalog")
    
    query = f"SELECT * FROM `{table_ref}`"
    results = client.query(query).result()
    
    # Convert BigQuery Row objects into standard Python dictionaries
    return [dict(row) for row in results]

def claim_reward(user_id: str, reward_id: str) -> bool:
    """Log that a user claimed a specific reward."""
    table_ref = _get_table_ref("user_claimed_rewards")
    
    rows_to_insert = [{
        "user_id": user_id,
        "reward_id": reward_id
    }]
    
    errors = client.insert_rows_json(table_ref, rows_to_insert)
    
    if errors:
        print(f"Errors inserting into user_claimed_rewards: {errors}")
        return False
    return True